# Site settings
author: Thomas Wright
title: Twiddle Wakka
header-img: img/home-bg.png
email: twwright@gmail.com
copyright_name: Thomas Wright
description: > # this means to ignore newlines until "baseurl:"
  brief explorations of coding concepts
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  twwright

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
